name: CI

on:
  push:
    branches:
      - master
      - 'v*' # older version branches
    tags:
      - '*'

  pull_request: {}
  schedule:
  - cron:  '0 6 * * 0' # weekly, on sundays

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: install dependencies
      run: yarn install --frozen-lockfile --ignore-engines
    - name: lint
      run: yarn lint:js

  node-tests:
    name: "Node: Node ${{ matrix.node }} - ${{ matrix.os }}"
    runs-on: "${{matrix.os}}-latest"
    timeout-minutes: 5

    strategy:
      matrix:
        os: ['ubuntu', 'windows', 'macOS']
        node: ['6', '8', '10', '12', '14']
        exclude:
          # excludes node 14 on macOS, this is because
          # ember-cli (until ~ 3.12) calls
          # `fs.writeFileSync('./tmp/.metadata_never_index)` on macOS platforms
          # to instruct spotlight to avoid indexing the local tmp folder
          # unfortunately, ember-cli does not pass a value for second arg (the
          # content to write) and Node 14 added an assertion
          #
          # TODO: delete this when we have dropped Node 6 and can update
          # ember-cli to a version that doesn't do this
          - os: 'macOS'
            node: '14'

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: install dependencies
      run: yarn install --frozen-lockfile --ignore-engines
    - name: test
      run: yarn test:node

  acceptance-tests:
    name: "Acceptance: Node ${{ matrix.node }} - ${{ matrix.os }}"
    runs-on: "${{matrix.os}}-latest"
    timeout-minutes: 5

    strategy:
      matrix:
        os: ['ubuntu', 'windows']
        node: ['12', '14']
        exclude:
          # excludes node 14 on macOS, this is because
          # ember-cli (until ~ 3.12) calls
          # `fs.writeFileSync('./tmp/.metadata_never_index)` on macOS platforms
          # to instruct spotlight to avoid indexing the local tmp folder
          # unfortunately, ember-cli does not pass a value for second arg (the
          # content to write) and Node 14 added an assertion
          #
          # TODO: delete this when we have dropped Node 6 and can update
          # ember-cli to a version that doesn't do this
          - os: 'macOS'
            node: '14'

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: install dependencies
      run: yarn install --frozen-lockfile --ignore-engines
    - name: test
      run: yarn test:ember

  floating-test:
    name: Floating dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: install dependencies
      run: yarn install --no-lockfile --ignore-engines
    - name: test
      run: yarn test

